version: '3.8'

services:
  app:
    build: 
      context: ./
      dockerfile: dockerfiles/app/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/vite-project
      - /vite-project/node_modules
    depends_on:
      - db
  db:
    build:
        context: ./
        dockerfile: dockerfiles/sql/Dockerfile
    environment: 
        MYSQL_DATABASE: blog_db
        MYSQL_USER: blog_user
        MYSQL_PASSWORD: blog_pass44
        MYSQL_ROOT_PASSWORD: root_pass44
    ports:
        - "3383:3306"
    volumes:
        - ./mysql-data:/var/lib/mysql